version: 2

sphinx:
  configuration: source/conf.py

python:
  version: "3.7"
  # Install our python package before building the docs
  install:
    - requirements: requirements.txt

formats:
  - pdf
  - epub
