version: 2

build:
  tools:
    python: "3.12"

sphinx:
  configuration: source/conf.py

python:
  # Install our python package before building the docs
  install:
    - requirements: requirements.txt

formats:
  - pdf
  - epub
